#!/bin/bash
echo "================================="
echo "     ESP32 DEVELOPMENT HELPER"
echo "================================="

echo ""
echo "📟 PLATFORMIO COMMANDS"
echo "  pio run              - Build project"
echo "  pio run -t upload    - Build and upload"
echo "  pio device monitor   - Serial monitor"
echo "  pio pkg install      - Install libraries"
echo "  pio update           - Update PlatformIO"

echo ""
echo "🔌 COMMON GPIO PINS"
echo "  Built-in LED: GPIO2"
echo "  I2C:"
echo "    SDA - GPIO21"
echo "    SCL - GPIO22"
echo "  SPI:"
echo "    MOSI - GPIO23"
echo "    MISO - GPIO19"
echo "    SCK  - GPIO18"
echo "    CS   - GPIO5"

echo ""
echo "⚠️  INPUT-ONLY PINS (no internal pullup)"
echo "  GPIO34, GPIO35, GPIO36, GPIO39"

echo ""
echo "💡 TROUBLESHOOTING"
echo "  1. Check port: ls /dev/ttyUSB*"
echo "  2. Upload issues? Hold BOOT button"
echo "  3. Serial monitor baud rate: 115200"
echo "  4. Check WiFi credentials"
